version: '3'

services:
  app:
    build: 
      context: .
    command: python -u app.py
    volumes:
      - .:/app
    ports:
      -  "5001:5000"
    links:
      - db

  db:
    image: mongo:latest
    hostname: project_mongodb
    environment:
      - MONGO_INITDB_DATABASE = user_db
      - MONGO_INITDB_USERNAME = root
      - MONGO_INITDB_PASSWORD = pass 
    volumes:
      - ./init-fb.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"